import fs from 'node:fs/promises';
import path from 'node:path';
import { pathToFileURL } from 'node:url';
const artifactEntry=path.resolve(path.dirname(process.execPath),'../node_modules/@oai/artifact-tool/dist/artifact_tool.mjs');
const { Workbook, SpreadsheetFile } = await import(pathToFileURL(artifactEntry).href);
const root=path.resolve(process.argv[2]||'06_市场研究/01_竞品/行业标杆店铺拆解');
const preview=path.resolve(process.argv[3]||'99_临时区/行业标杆研究');
await fs.mkdir(preview,{recursive:true});
const rows=JSON.parse(await fs.readFile(root+'/数据/kaisuntd-clean.json','utf8'));
const stats=JSON.parse(await fs.readFile(root+'/数据/analysis-summary.json','utf8'));
const wb=Workbook.create();
const summary=wb.worksheets.add('采集分析');
const detail=wb.worksheets.add('凯顺商品');
const end=rows.length+4;
detail.getRange('A1').values=[['凯顺公开目录，采集于2026-10-11；第1—34页，共55页']];
detail.getRange('A2').values=[['成交周期、单位及计价单位待核；空白成交不等于零。分类按标题初筛。原件以JSON保存。']];
detail.getRange('A4:O4').values=[['商品ID','标题意图分类','原标题','标题字符','MOQ数量','MOQ单位','公开sold显示','价格下限USD','价格上限USD','计价单位','采集日期（北京时间）','商品来源','主图来源','主图实看','目录页']];
detail.getRange(`A5:O${end}`).values=rows.map(r=>[r.product_id,r.category,r.title,r.title_characters,r.moq_quantity,r.moq_unit,r.sold_display,r.price_min_display,r.price_max_display,r.price_unit,new Date(Date.parse(r.observed_at)+8*60*60*1000),r.url,r.image_url,r.image_visual_review,r.page]);
detail.tables.add(`A4:O${end}`,true,'KaisunProducts');
detail.freezePanes.freezeRows(4);detail.freezePanes.freezeColumns(1);
detail.getRange(`D5:E${end}`).setNumberFormat('#,##0');detail.getRange(`G5:G${end}`).setNumberFormat('#,##0');
detail.getRange(`H5:I${end}`).setNumberFormat('0.00');detail.getRange(`K5:K${end}`).setNumberFormat('yyyy-mm-dd');
detail.getRange(`O5:O${end}`).setNumberFormat('0');
summary.getRange('A2').values=[['凯顺店铺拆解：当前采集分析']];
summary.getRange('A4:B4').values=[['采集状态','部分完成，滑块验证待处理']];
summary.getRange('A5:B7').values=[['已采集页',stats.completed_pages],['目录总页',stats.expected_pages],['页覆盖率',null]];
summary.getRange('B7').formulas=[['=B5/B6']];summary.getRange('B7').setNumberFormat('0.0%');
summary.getRange('A9:A12').values=[['唯一商品ID'],['显示成交数量的商品'],['未显示成交数量的商品'],['标题字符中位数']];
summary.getRange('B9:B12').formulas=[[`=COUNTA('凯顺商品'!A5:A${end})`],[`=COUNT('凯顺商品'!G5:G${end})`],['=B9-B10'],[`=MEDIAN('凯顺商品'!D5:D${end})`]];
summary.getRange('A14:C14').values=[['标题意图分类','链接数量','占已采集链接']];
const cats=Object.keys(stats.categories);
summary.getRange(`A15:A${14+cats.length}`).values=cats.map(x=>[x]);
for(let i=0;i<cats.length;i++){const r=15+i;summary.getRange(`B${r}:C${r}`).formulas=[[`=COUNTIFS('凯顺商品'!B$5:B$${end},A${r})`,`=B${r}/$B$9`]];}
summary.getRange(`C15:C${14+cats.length}`).setNumberFormat('0.0%');
summary.getRange('E4').values=[['当前决策']];
summary.getRange('E5').values=[['标题先明确鞋型、穿脱方式、使用需求，再放可兑现的定制信息。']];
summary.getRange('E7').values=[['主图先让采购商看清结构；不要直接照搬FREE DESIGN承诺。']];
summary.getRange('E9').values=[['300双定制与低起订商品分别对标，不用大单价格比较2双试单。']];
summary.getRange('E11').values=[['销量榜身份、未采集21页、详情计价单位与转化因果仍待核。']];
summary.getRange('E13').values=[['此表统计已采集544条；不能代表全店或全行业比例。']];
const candidates=JSON.parse(await fs.readFile(root+'/数据/对标店铺.json','utf8')).candidates;
const other=wb.worksheets.add('其他候选店铺');
other.getRange('A1').values=[['2026-10-11；单关键词第一页商品卡，非行业店铺销量榜；全目录和主图待核']];
other.getRange('A3:I3').values=[['店铺域名','商品ID','原标题','公开sold显示','MOQ数量','MOQ原单位','研究优先级','商品来源','全目录状态']];
other.getRange('A4:I'+(candidates.length+3)).values=candidates.map(r=>[r.store_domain,r.product_id,r.title,r.sold_display,r.moq_quantity,r.moq_unit,r.priority,r.url,r.full_catalog_status]);
other.tables.add('A3:I'+(candidates.length+3),true,'OtherCandidates');
const review=JSON.parse(await fs.readFile(root+'/视觉证据/主图实看.json','utf8')).items;
const visual=wb.worksheets.add('20张主图实看');
visual.getRange('A1').values=[['2026-10-11；代表样本，非随机全店统计；全部原件及来源在本地主图对照册']];
visual.getRange('A3:F3').values=[['商品ID','公开sold显示','可见构图','服务覆盖','可见文案','观察及待核']];
visual.getRange('A4:F'+(review.length+3)).values=review.map(r=>[r.product_id,rows.find(x=>x.product_id===r.product_id).sold_display,r.visible,r.service_overlay?'有':'未见',r.message,r.note]);
visual.tables.add('A3:F'+(review.length+3),true,'VisualReview');
for(const sh of [other,visual]){sh.showGridLines=false;sh.freezePanes.freezeRows(3);sh.getUsedRange().format.font={name:'Arial',size:10};sh.getUsedRange().format.columnWidth=24;sh.getUsedRange().format.rowHeight=65;sh.getUsedRange().format.wrapText=true;sh.getRange(sh===other?'A3:I3':'A3:F3').format={fill:'#293B53',font:{color:'#FFFFFF',bold:true},rowHeight:30};}
for(const sh of [other,visual]){sh.getUsedRange().format.verticalAlignment='center';sh.getRange('A1').format.wrapText=false;sh.getRange('A1').format.rowHeight=28;sh.getRange('A2').format.rowHeight=12;}
other.getRange('A3:A9').format.columnWidth=34;
other.getRange('C3:C9').format.columnWidth=65;other.getRange('G3:G9').format.columnWidth=42;
other.getRange('B4:B9').setNumberFormat('0');other.getRange('D4:E9').setNumberFormat('0');
visual.getRange('A4:B23').setNumberFormat('0');visual.getRange('C3:C23').format.columnWidth=48;visual.getRange('F3:F23').format.columnWidth=70;
for(const sh of [summary,detail]){sh.showGridLines=false;sh.getUsedRange().format.font={name:'Arial',size:10};sh.getUsedRange().format.verticalAlignment='center';}
summary.getRange('A2').format.font={size:14,bold:true};summary.getRange('A4:C25').format.rowHeight=24;
summary.getRange('A4:A25').format.columnWidth=34;summary.getRange('B4:C25').format.columnWidth=17;
summary.getRange('D4:D25').format.columnWidth=3;summary.getRange('E4:E25').format.columnWidth=88;
for(const range of ['A14:C14','E4'])summary.getRange(range).format={fill:'#293B53',font:{color:'#FFFFFF',bold:true},rowHeight:26};
summary.getRange('B4').format.fill='#FFF2D9';
detail.getRange(`A4:O${end}`).format.rowHeight=56;
detail.getRange(`A4:O${end}`).format.columnWidth=20;
detail.getRange(`C4:C${end}`).format.columnWidth=70;detail.getRange(`C5:C${end}`).format.wrapText=true;
detail.getRange(`B4:B${end}`).format.columnWidth=30;detail.getRange(`J4:J${end}`).format.columnWidth=36;
detail.getRange(`D4:I${end}`).format.columnWidth=16;detail.getRange(`L4:M${end}`).format.columnWidth=38;
detail.getRange('A5:A'+end).setNumberFormat('0');
detail.getRange('A4:O4').format={fill:'#293B53',font:{color:'#FFFFFF',bold:true},rowHeight:28,horizontalAlignment:'center'};
wb.recalculate();
const report=await wb.inspect({kind:'table',range:'采集分析!A4:C25',include:'values,formulas',tableMaxRows:24,tableMaxCols:3});
console.log(report.ndjson);
console.log((await wb.inspect({kind:'match',searchTerm:'#REF!|#DIV/0!|#VALUE!|#NAME\\?|#N/A|#NUM!|#NULL!',options:{useRegex:true,maxResults:10},summary:'error scan'})).ndjson);
for(const [sheetName,range,name] of [['采集分析','A1:E25','summary'],['凯顺商品','A1:I9','detail'],['其他候选店铺','A1:G9','candidates'],['20张主图实看','A1:F7','visual']]){const img=await wb.render({sheetName,range,scale:1,format:'png'});await fs.writeFile(path.join(preview,name+'.png'),new Uint8Array(await img.arrayBuffer()));}
await (await SpreadsheetFile.exportXlsx(wb)).save(root+'/凯顺竞品分析.xlsx');
console.log('Exported '+rows.length+' rows');
